resources:
  - name: from_artifactory
    type: IncomingWebhook
    configuration:
      webhookName: from_artifactory
 
pipelines:
  - name: basic_pipeline_webhook
    steps:
    - name: step_1
      type: Bash
      configuration:
        inputResources:
          - name: from_artifactory
        integrations:
           - name: myArtifactory
      execution:
          onExecute:
            - echo "$res_from_artifactory_payload" | jq '.' > payload.json
            - export FILE_PATH= read_json payload.json "data.path"
            - export FILE_REPO= read_json payload.json "data.repo_key"
            - retry_command jfrog rt config --url $int_myArtifactory_url --user $int_myArtifactory_user --apikey $int_myArtifactory_apikey --interactive=false
            - download_file="$FILE_REPO/$FILE_PATH"
            - jfrog rt dl $download_file .
            - ls -la
            
          
          
          


