resources:
  - name: from_artifactory
    type: IncomingWebhook
    configuration:
      webhookName: from_artifactory
 
pipelines:
  - name: basic_pipeline_webhook
    steps:
    - name: step_1
      type: Bash
      configuration:
        inputResources:
          - name: from_artifactory
        integrations:
           - name: myArtifactory
      execution:
          onExecute:
            - retry_command jfrog rt config --url $int_myArtifactory_url --user $int_myArtifactory_user --apikey $int_myArtifactory_apikey --interactive=false
            - echo "$res_from_artifactory_payload" | jq '.' > payload.json
            - file_path=$(read_json payload.json 'data.path')
            - file_repo=$(read_json payload.json 'data.repo_key')
            - downloadfile="${file_repo}/${file_path}"
            - echo $downloadfile
            - jfrog rt dl $downloadfile /
            - ls -la
            
          
          
          


